apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-fs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: tcloud-public-evs-manual
