apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-retain-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: tcloud-public-evs-retain
