apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tcloud-public-evs-manual
provisioner: csi.evs.tcloudpublic.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  volumeType: SSD
