apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.evs.tcloudpublic.com
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Persistent
