apiVersion: v1
kind: Secret
metadata:
  name: tcloud-public-csi-cloud-config
  namespace: tcloud-public-csi-system
type: Opaque
stringData:
  OS_AUTH_URL: https://iam.example.com/v3
  OS_REGION: eu-de
  OS_AVAILABILITY_ZONE: eu-de-01
  OS_DOMAIN_NAME: Default
  OS_USERNAME: replace-me
  OS_PASSWORD: replace-me
  OS_PROJECT_ID: replace-me
